### ISSUE TITLE
haproxy 1.8

### ISSUE THREAD

**Issue by emper0r** [uoi-io/ansible-haproxy#25]
Hi, can you confirm could be use on 1.8 version on CentOS ?

**Comment by goldyfruit** [comment]
Hi @emper0r it should be, it would be great if you could confirm it :)
:+1:

**Comment by emper0r** [comment]
Hi again, .. well yes with haproxy == 1.8.24 where I'm testing and with a little different config had to added this lines:

```
git diff templates/haproxy.cfg.j2
diff --git a/templates/haproxy.cfg.j2 b/templates/haproxy.cfg.j2
index 189284d..61e9733 100755
--- a/templates/haproxy.cfg.j2
+++ b/templates/haproxy.cfg.j2
@@ -150,6 +150,11 @@ frontend {{ name }}
     capture         {{ cap }}
                 {% endfor %}
             {% endif %}
+            {% if value.acls is defined %}
+                {% for acl in value.acls %}
+    acl             {{ acl }}
+                {% endfor %}
+            {% endif %}
             {% if value.options is defined %}
                 {% for opt in value.options %}
     option          {{ opt }}
@@ -196,6 +201,11 @@ frontend {{ name }}
     redirect        {{ redirect }}
                 {% endfor %}
             {% endif %}
+            {% if value.rspireps is defined %}
+                {% for rspirep in value.rspireps %}
+    rspirep         {{ rspirep }}
+                {% endfor %}
+            {% endif %}
             {% if value.logs is defined %}
                 {% for log in value.logs %}
     log             {{ log }}
```

acl and rspirep can be exist as syntax on frontend space.

**Comment by goldyfruit** [comment]
@emper0r Thanks for the feedback, do you think tou could write a PR?

**Comment by emper0r** [comment]
yes of course....but @goldyfruit checking into manual this changes can be True for 1.8 version and reading the stable version is deprecated so... I guess your version would be better.... but can be more modular if you check all matrix to possible options to will add into template...
checkout: http://cbonte.github.io/haproxy-dconv/2.0/snapshot/configuration.html#4.1
