### ISSUE TITLE
How to use Ansible-Haproxy?

### ISSUE THREAD

**Issue by funky81** [uoi-io/ansible-haproxy#26]
Hi,

Just wondering, how to use this ansible-haproxy?
It looks promising to use.

Thanks

**Comment by dsavineau** [comment]
Like any other ansible roles.

https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#using-roles

You can have more information about the variables or examples at https://github.com/uoi-io/ansible-haproxy/blob/master/README.md
