### ISSUE TITLE
ansible.errors.AnsibleUndefinedVariable: 'haproxy_stats_listener_options' is undefined

### ISSUE THREAD

**Issue by bcg62** [uoi-io/ansible-haproxy#47]
haproxy_stats_listener_options is not set by default but referenced by the template causing a failure.

should this be uncommented and defaulted as `haproxy_stats_listener_options: []` ?

https://github.com/uoi-io/ansible-haproxy/commit/3abed7d99712f97e209cbab151a0fe3dd92c1bad#diff-23e21b6c89468f7534697ad091835b3ee5e0213b37ace489488234e5a9548ec4R95

**Comment by goldyfruit** [comment]
Hi @bcg62 

Thanks for the issue, feel free to create a PR, I'll review it and merge it.
Otherwise, I'll try to fix that soon as possible.
 :+1:
