### ISSUE TITLE
Missing options http-request in listen stats block

### ISSUE THREAD

**Issue by acaz** [uoi-io/ansible-haproxy#52]
Hello

I have to add some options in template file , haproxy-stats.cfg.j2
I use the integrated prometheus exporter for haproxy. 
So i have to declare
http-request     use-service prometheus-exporter if { path /metrics }

To do this, i have added this block in haproxy-stats.cfg.j2 

```
{% for listener_httprequest in haproxy_stats_listener_httprequest %}
    http-request     {{ listener_httprequest }}
{% endfor %}
```

```
....
{% for listener_opt in haproxy_stats_listener_options %}
    option     {{ listener_opt }}
{% endfor %}
{% for listener_httprequest in haproxy_stats_listener_httprequest %}
    http-request     {{ listener_httprequest }}
{% endfor %}
    timeout    client 100s
....
```

Is it possible to update the role and integrate http-request  directives ? 

Regards

Arnaud

**Comment by goldyfruit** [comment]
Hi @acaz 

Feel free to create a PR with this change, I'll review it.

Thanks!

**Comment by goldyfruit** [comment]
I close this issue, feel free to re-open when the PR is pushed.
