### ISSUE TITLE
Improve idempotency in configuration file

### ISSUE THREAD

**Issue by haydenseitz** [uoi-io/ansible-haproxy#53]
Including a timestamp in the config file makes the task show as CHANGED on each run, and also forces the haproxy reload handler to run each time. Maybe instead include a role variable to toggle the timestamp on/off in the file?

https://github.com/uoi-io/ansible-haproxy/blob/5d9f014fe420dd4c38e14e303695962c87221854/templates/etc/haproxy/haproxy.cfg.j2#L4

**Comment by goldyfruit** [comment]
Hi @haydenseitz,

Please fill free to open a PR with the fix, I'll review it.

Thanks

**Comment by goldyfruit** [comment]
I did the change.
Feel free to re-open the issue.

**Comment by haydenseitz** [comment]
Ah, thanks. Didn't see this until my PR showed a conflict 😬

**Comment by goldyfruit** [comment]
I just pushed a new release on Galaxy.
