### ISSUE TITLE
Can't define multiple http_check options

### ISSUE THREAD

**Issue by marcin-github** [uoi-io/ansible-haproxy#56]
Hello!
`http-check` can be defined in backend multiple times, e.g
`http-check send ....`
`http-check expect ...`
but now I can see possibility to configure it in role. May I request for adding this feature?

**Comment by goldyfruit** [comment]
Hi @marcin-github 

Please fill free to push a PR, I'll review it.

**Comment by goldyfruit** [comment]
Implemented by PR #60 
Thanks @magenbrot

**Comment by marcin-github** [comment]
Thank you!
