### ISSUE TITLE
[question] How to add "http-reuse <foo>" to section e.g. "defaults"?

### ISSUE THREAD

**Issue by marcin-github** [uoi-io/ansible-haproxy#69]
Hi,
when I tried add `http-reuse` to configuration of haproxy I couldn't find a way to achieve it. There is no problem if I need add `option foo bar` but what to do if configuration key doesn't start from `option ...`?

**Comment by goldyfruit** [comment]
Hi @marcin-github 

Sorry for the late answer, feel free to open a PR, I'll review it :+1:
